### ISSUE TITLE
Parallelize tests

### ISSUE THREAD

**Issue by DariusParvin** [boltlabs-inc/zeekoe#282]
Right now our tests scenarios must be run in serial. This is because:
1 - we use the same tezos accounts for all the tests
2 - zeekoe creates operations independently of each other, which can cause errors/conflicts if two operations are created at the same time (see #212)

When our tests become more extensive, we may want to consider parallelizing the tests by using multiple accounts, multiple sandbox instances, or coordinating the tests so that they don't have conflicting on-chain operations.

**Comment by marsella** [comment]
This remains a problem with the existing Tezos infrastructure. I see several possible outcomes here:
- we update that infrastructure per #212. I don't anticipate us building out a better Tezos operations manager / node, so this will likely only happen if they provide one and we integrate it.
- we implement the testing infrastructure described in #69. Then, parallelizing tests becomes a runtime flag, and can easily be switched on or off for different chains

I don't expect that we will build out a complex infrastructure of multiple sandboxes, etc. to speed up our testing. These tests are currently run overnight, so timing is not an issue. I am going to close this issue, because I don't think there is a concrete task that is not addressed by the other linked issues.
